[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", features = ["serde", "std"] }
sea-orm = { version = "1.1.3", features = ["chrono", "with-chrono"] }
serde = { version = "1.0.217", features = ["derive"] }

