apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  labels:
    app: wallet-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
      - name: wallet-service
        image: marcusantunius/wallet-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: RUST_LOG
          value: "info"
---